### ISSUE TITLE
[tracking] Initial version requirements

### ISSUE THREAD

**Issue by dgw** [dgw/sopel-admindb#1]
Requirements list still in flux. Major requirements will be split out into separate issues eventually, to keep this tracking issue relatively clean.

Before being declared "complete", the initial version of this module must be able to support the following:
- [ ] Connect to a database specified in `bot.config.admindb.*` fields
  - [ ] Accept and execute SQL queries against the configured database
    - [ ] Restrict SQL execution to `owner` or `admin`s, based on `bot.config.admindb.require`
    - Return the results of `SELECT` statements (see #4)
